### ISSUE TITLE
Adding multiple words at once

### ISSUE THREAD

**Issue by PaddiM8** [Alamantus/Lexiconga#12]
I think I saw somewhere that I can do requests here too, so...

I think it would be awesome if you would just give the website a list and so it will add
words automatically, and if the Part of Speech isn't specified, make it generate it automactially using like wordsapi.com or something. I have a list in a excel file that I'd like to import quickly to this site.

**Comment by Alamantus** [comment]
I've been thinking about adding support for importing CSV files for a while, so that's a good idea to have on the radar!

While WordsAPI is a good idea, I won't include automatic part of speech recognition. Instead, I'll have it import as blank and then add a filter option for "blank" or something to help with the cleanup process. Since the parts of speech for a dictionary is already completely customizable, it'll just be the user's responsibility to input their own parts of speech correctly.

**Comment by PaddiM8** [comment]
That sounds great! :D I meant that the automatic process can be life saving
if you have a lot of words! I would actually need it. Would be good if you
could choose to do it on the words with plank part of speech, yeah.

onsdag 8 juni 2016 skrev Robbie Antenesse <notifications@github.com>:
> I've been thinking about adding support for importing CSV files for a
while, so that's a good idea to have on the radar!
>
> While WordsAPI is a good idea, I won't include automatic part of speech
recognition. Instead, I'll have it import as blank and then add a filter
option for "blank" or something to help with the cleanup process. Since the
parts of speech for a dictionary is already completely customizable, it'll
just be the user's responsibility to input their own parts of speech
correctly.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/cAdzYf587WLDufeJcfiQ8xblmee98uGB0u0qeFTPiF3Zb-kcOqQMLOSlKpxnot4mnhfMgzHGYG_uA3ikZ7eGxrUAo49moHqfOF2SGWP8-Yk3kXkAghIrcrkAF4XoAZmJAXVlRfB0po_o5nsb1tVSzpu_A6Ki_Q=s0-d-e1-ft#https://github.com/notifications/beacon/AS55lIuv9VT0ffFopuXxPWZRGoTAa_YYks5qJvDFgaJpZM4IxJfE.gif
>

**Comment by Alamantus** [comment]
Importing words has been added in the Jun-29-2016 release!
