### ISSUE TITLE
HTML markup isn't automatically ended

### ISSUE THREAD

**Issue by osswix** [Alamantus/Lexiconga#13]
If you for example use `<b>` in one of the word entry fields it bolds everything underneath too (including other word entries), maybe implement something that automatically closes HTML tags.

**Comment by Alamantus** [comment]
This actually brings up a completely different issue. The fact that you can use HTML markup is a mistake—it should only allow Markdown, so I'll work on making sure only Markdown works, not HTML.

Unfortunately that means that you'll need to re-do any HTML styling you did, but it'll actually prevent this kind of problem because the Markdown won't render at all if you miss an ending.

**Comment by Alamantus** [comment]
I've uploaded a patch that prevents HTML manually written in dictionaries from rendering. Only [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) should be used in Lexiconga entries.

This will prevent HTML tags being incomplete because Markdown will only render if it is entered correctly.

**Comment by osswix** [comment]
pretty sad as i liked using html.

**Comment by Alamantus** [comment]
Yeah, sorry about that, but it's necessary for security. Fortunately, Markdown is really easy to use and learn and actually does the same things HTML does a lot faster than typing out HTML.
