### ISSUE TITLE
Part of Speech field gets truncated

### ISSUE THREAD

**Issue by tsela** [Alamantus/Lexiconga#15]
Sorry for adding an issue so soon, but I noticed what seems to be a bug.
For my Haotyétpi language, I have a relatively large list of parts of speech. When I input them in the field in the Settings window everything works fine, and I can use all these parts of speech correctly. They also correctly appear in the .dict file (I checked). However, when I log in with my account, the list gets truncated to 71 characters (if I counted correctly). AFAIK this does not happen when I simply close the browser and open it again, only when I log in, or when I change dictionaries in the Settings. This is very impractical because it means I have to re-input the parts of speech every time I'm logging in...

**Comment by Alamantus** [comment]
Hey, thanks for catching this! And don't apologize—I need everyone's help to catch all of the issues. :)

I think I know exactly what the problem is: the database might be set up to only allow a certain number of characters for the Parts of Speech field. It should be easy enough to fix, and I'll look into it as soon as I am able. I'll comment again with updates when I'm working on it!

**Comment by Alamantus** [comment]
Hi @tsela,

I was able to look at the database and confirm my suspicion—the Part of Speech field was limited to 100 characters. I've raised that to 500 characters, so hopefully that will be enough for you! If it's not, please let me know and I can expand it further.

**Comment by tsela** [comment]
Hi,

Unfortunately that's not enough :(. My list of parts of speech is 1287 characters long :(. Maybe I should use abbreviations, although I like it this way (I'm being very precise with my parts of speech, but I think the structure of the language asks for it).

**Comment by Alamantus** [comment]
Good heavens, that's a lot. Well it's probably safe to say that your language will be an outlier—most conlangers will keep a more basic list of parts of speech. At any rate, I've increased it to 1500 characters. I would make it unlimited, but I wouldn't be able to have the default values if I did. As long as you don't add too many more parts of speech, you'll hopefully be okay...

Do know that having so many parts of speech is going to make your filter checklist in the search panel really messy, though. That can't be fixed by anything other than decreasing the number of specified parts of speech. Maybe one way you can organize it is by having a smaller group of parts of speech and include more specific details in the Long Definition field? But hey, if you don't mind the long list of checkboxes, then more power to you! :)

**Comment by tsela** [comment]
Well, I don't mind the long search panel, and I like the extremely explicit list of parts of speech. Also, basically my description of Haotyétpi parts of speech is actually a hierarchy, with three roots (Nominals, Verbals and Particles), and the actual parts of speech branching from under them. The list contains basically all the leaves of these three trees :).
I may remove a few parts of speech in the future (especially those that are marked as "archaic"), but I'm working from basically a spreadsheet type of dictionary, without much space for definitions, and I needed the explanatory power of many parts of speech there. As I am working more with Lexiconga, I will adapt things to it, and will probably shorten the list of parts of speech slightly.
In any case, thanks for adapting your tool to my needs. I hope having such long text fields won't tax your database server too much!
