### ISSUE TITLE
Add Additional Notes Fields to Linguistics Details

### ISSUE THREAD

**Issue by marrus-sh** [Alamantus/Lexiconga#27]
My language has 14 valid consonants (/g/, /k/, …) in the onset, and each of these consonants may be followed by a medial (/w/, /j/, …). This produces far too many combinations (/gw/, /kw/, …, /gj/, /kj/, …) to list them all in the “Onset” category of phonotactics.

It would be beneficial to have a “Medial” category in order to denote the existence of these kinds of combinations.

See [the Chinese model](https://en.wikipedia.org/wiki/Syllable#Chinese_model) for syllable structure.

**Comment by Alamantus** [comment]
Thanks for this! I have minimal linguistics experience, and even less beyond English, so these kinds of requests are very helpful for me to know what will be helpful to others!

I will work on this and include it in the first round of feature updates. There is no planned date for the first round yet, so for now I would keep this information in either the Description or in the Exceptions field to keep track of it for now!

**Comment by osswix** [comment]
Hello, just booping in with some linguistics things.

The medial can be considered part of both the onset and the nucleus and is generally seen as a subset of those. I think that in the phonotactics section you should work with groups rather than with individual sounds. (say C for a single consonant, M for a medial, V for a vowel etc.) and further explain those groups in a section below rather than listing every possibility.

for example setting;

- onset : C
- nucleus : V, MV
- coda : F

and then have a section where you can explain the groups (i would currently just do this in the "exceptions" part). By writing something alike to the following as an example example.
>  "C can be any consonant, V can be any vowel, M can be any of the medial sounds /w/ and /j/ and F can be any of the final consonants /t/ and /k/. Only the Vowel is actually required to form a syllable, other parts are optional"

so maybe instead of creating more groups and complicating the system, add another field to explain groupings as is normally done in grammars to my knowledge when explaining the structure of syllables in a language. Or the ability to set up the groups ourselves (instead of onset nucleus coda also the possibility to add a medial inbetween the onset and nucleus, or group nucleus and coda into rhime. etc.)

handy readup on this:
https://en.wikipedia.org/wiki/Syllable

**Comment by Alamantus** [comment]
@osswix thanks for the insight! I do think this a much better idea, and I think instead of expanding the phonotactics fields, I'll add a "Notes" field above the "Exceptions" field _or_ maybe I'll just rename "Exceptions" to "Notes," because then you could include Exceptions _and_ any other details.

I'm honestly not sure anymore why I went with Exceptions instead of Notes at this point...

Would that be acceptable, or do you think it's important to have a separate Exceptions field?

**Comment by osswix** [comment]
sounds fine to me
