### ISSUE TITLE
Add example sentence tools

### ISSUE THREAD

**Issue by Aksej** [Alamantus/Lexiconga#38]
An example sentence has a text part, whose parts (not necessarily only whole words) can be linked to dictionary entries.
The example sentences are in return displayed automatically in the respective dictionary entries, maybe hidden by standard.

**Comment by Alamantus** [comment]
@Aksej The problem with this request is that it completely excludes users whose languages either require a lot of conjugation or have a lot of different parts of speech. Even if I allow programming sentences with a format like `{Adjective} {Noun} {Verb} {Noun} {Preposition}` or whatever, the result would be lackluster and nonsensical at best.

The only solution would be to add grammar table that would allow users to make Lexiconga conjugate for them and then add extra fields to allow users to chunk up their words into grammatical parts, but that's something I will not be adding to Lexiconga because the goal is to keep Lexiconga lean, light, and fast.

The best way to share example sentences is to write the sentences manually in the Description of the dictionary or the Details of a word and reference the words used with the `{{reference}}` syntax.

Does that make sense?

**Comment by Aksej** [comment]
Yes, makes sense, though I was less thinking of a sentence construction kit or something that would do the matching, but rather basically having a set of description fields with `{{reference}}` syntax (I'll have to check out how that works) independent of the dictionary itself.
I'm mostly asking because, so far, I am using the proposed method (well, apart from the references) and it's a pain to keep example sentences synced across entries.

**Comment by Alamantus** [comment]
@Aksej Correct, it only links as a reference to the words as entered into the dictionary, no inflections applied because it only checks for exact matches.

What I was suggesting is manually write the example sentence as it would be written (with tense and all) and then write the references to the words used on the next line/paragrah. It's less elegant than what I think you're hoping for, but it gets the job done and (on the bright side) potentially gives periodic reminders of your conlang's grammar to readers.

For example in my conlang, [Gobahai](https://lexicon.ga/74), I could do:

> **fu sugo** **fuli**lib **gu** **fu**bi◦
>
> {{fu sugo}} ("fly") {{fuli}} (plural, definite "the birds") {{gu}} ("in") {{fu}} (definite "the air").
> 
> The birds fly in the air.

(Though maybe not a great example because Gobahai doesn't have much conjugation or word transformation aside from definite article and plural...)  
If given enough time, I would come up with a better format for it, but that should be serviceable, if a little bit tedious (the next feature wave's "Details Template" addition might be helpful, too, if you're doing it frequently).

At some point in the future, I imagine bulk word editing would be a helpful addition, too, though I'd need to figure out the best way to implement something like that.

**Comment by Aksej** [comment]
Ah, that makes more sense. Thanks for your support!
