### ISSUE TITLE
syncing issue

### ISSUE THREAD

**Issue by Yayaha02** [Alamantus/Lexiconga#45]
the dictionary on my phone and on my computer are not synced, even though I'm logged in on both devices

**Comment by Alamantus** [comment]
@Yayaha02 Hi! Thanks for putting in a ticket!  
I'd love to get this worked out for you, but I'm going to need a little bit more information about this in order to help you.

1. **In what way are they not syncing?**

- Are you missing whole word entries?
- Missing changes to words? 
  - Word name?
  - Word pronunciation?
  - Definition?
  - Details?
- Missing changes to Dictionary details?
  - Description?
  - Details?
    - Phonology?
    - Phonotactics?
    - Orthography?
    - Grammar?

2. **Do you have more than one dictionary?**

3. **What browsers (Chrome, Firefox, Internet Explorer, Safari, Edge, etc.) are you using?**
- On your computer
- On your phone

4. **What kind of devices and what version of that device are you using?**
- Your computer (Window, Mac, Linux? What version?)
- Your phone (iPhone, Android, Windows Phone, etc? What model and version?)

I may need more information after you answer these questions, but I'm eager to get this sorted out!

**Comment by Yayaha02** [comment]
turns out i wasn't logged in on the desktop version so now when I edit and add new words they are synced.

But when I -edit words- on while logged out, and then log in -they don't update- on the other platform no matter how many times I refresh. this happens on both devices.
Though when I -add new words- while logged out -they do update- on the other device when I log in then refresh. 

I have a computer with windows 10, and a samsung galaxy e5 android phone. I use chrome on both of them. I have only one dictionary

**Comment by Alamantus** [comment]
@Yayaha02 Awesome, thank you for clarifying! It sounds like this will take a bit of testing to figure out, but I'll try to work on it as soon as I'm able, and I'll let you know as soon as I figure it out!

**Comment by Alamantus** [comment]
@Yayaha02 I just want to thank you again for submitting this issue report! I had noticed the problem in the past, but didn't realize how big an issue it actually was. It turns out that the reason for it was a _really_ stupid mistake on my part—I had a variable in the wrong place, which essentially caused the program to say "Oh, there's a change? I won't update it!"

Oops.

I've just uploaded a fix for the problem, and it is syncing changes between devices correctly now!
