### ISSUE TITLE
settings of one dictionary completely overwritten by the settings of another

### ISSUE THREAD

**Issue by aobunau** [Alamantus/Lexiconga#72]
i'd imagine this was caused by me having 2 tabs open at the same time but i'm not sure. the words are all fine, but things like my orthography & phonology are all gone

**Comment by Alamantus** [comment]
Unfortunately Lexiconga can only handle one dictionary on your computer at a time. The most recently loaded dictionary will win out every time because when you switch dictionaries, it does in fact overwrite the local data of your dictionary with that of the dictionary you switched to. Your words were safe because Lexiconga saves updates to them individually, but dictionary settings are saved all at once. Since you switched to a different dictionary, the tab with your previous dictionary immediately became incorrect, and any changes made on that tab would be saved to the _new_ dictionary you switched to in the other tab, because that's what is now stored on your browser.

This is definitely a limitation of the way Lexiconga uses your browser's local storage, and it can't really be fixed since all browsers handle local storage in subtly different ways (eg. how much data is allowed to be stored). The only way I can think to fix this is to add a check that makes sure the visible dictionary always matches the currently stored dictionary by refreshing the page if the internal IDs ever become mismatched. This might cause some confusion to people, but it would at least prevent this same problem from happening again.

**Comment by aobunau** [comment]
ok. thank you
